---
title: "MPCS 53120 Final Project"
author: "Jason Goode & Jordan Zandi"
date: "May 29, 2018"
output: html_document
---


```{r warning=FALSE, message=FALSE}
rm(list=ls())
library(plyr)
library(lubridate)
library(dplyr)
library(ggplot2)
library(ROCR)
library(ggmap)
library(rpart)
library(curl)
library(jsonlite)
library(broom)
library(rgdal)
library(scales)
library(rpart.plot)
library(RColorBrewer)
library(randomForest)
library(ggRandomForests)


```


**Graph Injuries**  

```{r}
#d.in <- read.csv('~/Desktop/visionzero/data/final/injury_monthly_final.csv', header = TRUE)
d.in <- read.csv('~/Desktop/data_analysis/project/visionzero/data/final/injury_monthly_final.csv', header = TRUE)

#Filter out intersections w/o injuries
d.in <- d.in %>%
  filter(MN != 0)


#All Injuries
g <- ggplot(data = d.in, aes(x=month(MN,label=TRUE,abbr=TRUE), y=Injuries_COUNT)) + 
  geom_bar(stat="identity", fill="steelblue") + 
  labs(x = "Month", y = "Injuries") + 
  ggtitle("Monthly Injuries (2016)") 

plot(g)

#Pedestrian Injuries
g <- ggplot(data = d.in, aes(x=month(MN,label=TRUE,abbr=TRUE), y=PedInjurie_COUNT)) + 
  geom_bar(stat="identity", fill="steelblue")  + 
  labs(x = "Month", y = "Injuries") + 
  ggtitle("Pedestrian Injuries (2016)") 

plot(g)

#Bike Injuries
g <- ggplot(data = d.in, aes(x=month(MN,label=TRUE,abbr=TRUE), y=BikeInjuri_COUNT)) + 
  geom_bar(stat="identity", fill="steelblue") + 
  labs(x = "Month", y = "Injuries") + 
  ggtitle("Bike Injuries (2016)") 

plot(g) 

#Motor Vehicle Injuries
g <- ggplot(data = d.in, aes(x=month(MN,label=TRUE,abbr=TRUE), y=MVOInjurie_COUNT)) + 
  geom_bar(stat="identity", fill="steelblue") + 
  labs(x = "Month", y = "Injuries") + 
  ggtitle("Motor Vehicle Injuries (2016)") 

plot(g)

```

**Plot injuries to map**  

```{r}
d.in <- read.csv('~/Desktop/data_analysis/project/visionzero/data/final/injury_monthly_final.csv', header = TRUE)
#d.in <- read.csv('~/Desktop/visionzero/data/final/injury_monthly_final.csv', header = TRUE)

# Set a base map
nyc <- get_map(location = c(lon = -73.935, lat = 40.712), zoom = 11)

#Bike injuries by month
bike_inj <- d.in %>% filter(Injuries == 1 & BikeInjuri == 1)

g <- ggmap(nyc) + geom_point(data = bike_inj, aes(x = Lon, y = Lat, fill=month(MN,label=TRUE,abbr=TRUE)),size = 1, shape = 21)  + ggtitle("Bike Injuries (2016)") 

plot(g)

#bike_zones <- readOGR("http://www.nyc.gov/html/dot/downloads/misc/bike_priority_districts.json")
#g <- ggmap(nyc) + ggmap(bike_zones)
#multiplot(g, )

#Pedestrian injuries by month
ped_inj <- d.in %>% filter(Injuries == 1 & PedInjurie == 1)

g <- ggmap(nyc) + geom_point(data = ped_inj, aes(x = Lon, y = Lat, fill=month(MN,label=TRUE,abbr=TRUE)),size = 1, shape = 21) + ggtitle("Pedestrian Injuries (2016)") 

plot(g)

#MVO injuries by month
mvo_inj <- d.in %>% filter(Injuries == 1 & MVOInjurie == 1)

g <- ggmap(nyc) + geom_point(data = mvo_inj, aes(x = Lon, y = Lat, fill=month(MN,label=TRUE,abbr=TRUE)),size = 1, shape = 21) + ggtitle("Motor Vehicle Injuries (2016)") 

plot(g)


```

**Format variables **  

```{r}

#format dataset - turn variables into factors
d.in <- read.csv('~/Desktop/data_analysis/project/visionzero/data/final/injury_monthly_final.csv', header = TRUE)
#d.in <- read.csv('~/Desktop/visionzero/data/final/injury_monthly_final.csv', header = TRUE)

#transform variables into factors
d.in <- d.in %>%
  mutate(Injuries = as.factor(Injuries),
         PedInjurie = as.factor(PedInjurie),
         BikeInjuri = as.factor(BikeInjuri),
         MVOInjurie = as.factor(MVOInjurie),
         bike_priority_districts = as.factor(bike_priority_districts),
         enhanced_crossings = as.factor(enhanced_crossings),
         left_turn_traffic_calming = as.factor(left_turn_traffic_calming),
         neighborhood_slow_zones = as.factor(neighborhood_slow_zones), 
         leading_pedestrian_interval_signals = as.factor(leading_pedestrian_interval_signals), 
         signal_timing = as.factor(signal_timing), 
         speed_humps = as.factor(speed_humps), 
         safe_streets_for_seniors = as.factor(safe_streets_for_seniors),
         street_improvement_projects_corridors = as.factor(street_improvement_projects_corridors),
         vz_priority_corridors = as.factor(vz_priority_corridors),
         vz_priority_intersections = as.factor(vz_priority_intersections),
         arterial_slow_zones = as.factor(arterial_slow_zones), 
         MN = as.factor(MN),
         street_improvement_projects_corridors = as.factor(street_improvement_projects_corridors),
         vz_priority_zones = as.factor(vz_priority_zones))

  
```

**Multiple Logistic Regressions**
```{r}

#GLM - AllInjures (minus VZ & Bike Zone)
# VZ and Bike Zones are not street attributes - just known problem areas

injury_monthly.glm <- glm(Injuries ~ enhanced_crossings + speed_humps + left_turn_traffic_calming + arterial_slow_zones + leading_pedestrian_interval_signals + signal_timing + safe_streets_for_seniors + street_improvement_projects_corridors + neighborhood_slow_zones, family = "binomial", data = d.in)

summary(injury_monthly.glm)
exp(coef((injury_monthly.glm)))
exp(confint((injury_monthly.glm)))
    
#build table to plot Odds Ratios
a <- data.frame(exp(coef((injury_monthly.glm))))

a <- cbind(attribute = rownames(a), a)
rownames(a) <- 1:nrow(a)

b <- data.frame(exp(confint((injury_monthly.glm))))
b <- cbind(attribute = rownames(b), b)
rownames(b) <- 1:nrow(b)

coef_df <- left_join(a, b, by = "attribute")
colnames(coef_df)[2] <- "coefficient"
colnames(coef_df)[3] <- "lower_bound"
colnames(coef_df)[4] <- "upper_bound"

g <- ggplot(coef_df, aes(x = attribute, y = coefficient)) +
  geom_point(size = 2) +
  geom_errorbar(aes(ymax = upper_bound, ymin = lower_bound), width=0.1, color="darkred") + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) + 
  geom_text(data = coef_df, aes(label = round(coefficient, digits=3)), hjust = 1.2) +
  ggtitle("Injuries - Coefficients & Confidence Intervals")

plot(g)

#GLM - Pedestrian Injuries
ped_injury <- glm(PedInjurie ~ arterial_slow_zones + enhanced_crossings + speed_humps + left_turn_traffic_calming + leading_pedestrian_interval_signals + street_improvement_projects_corridors + neighborhood_slow_zones, family = "binomial", data = d.in)

summary(ped_injury)
exp(coef(ped_injury))
exp(confint(ped_injury))

#GLM - Pedestrian Injuries
#build table to plot Odds Ratios
a <- data.frame(exp(coef((ped_injury))))

a <- cbind(attribute = rownames(a), a)
rownames(a) <- 1:nrow(a)

b <- data.frame(exp(confint((ped_injury))))
b <- cbind(attribute = rownames(b), b)
rownames(b) <- 1:nrow(b)

coef_df <- left_join(a, b, by = "attribute")
colnames(coef_df)[2] <- "coefficient"
colnames(coef_df)[3] <- "lower_bound"
colnames(coef_df)[4] <- "upper_bound"

g <- ggplot(coef_df, aes(x = attribute, y = coefficient)) +
  geom_point(size = 2) +
  geom_errorbar(aes(ymax = upper_bound, ymin = lower_bound), width=0.1, color="darkred") + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) + 
  geom_text(data = coef_df, aes(label = round(coefficient, digits=3)), hjust = 1.2) +
  ggtitle("Pedestrian Injuries - Coefficients & Confidence Intervals")

plot(g)

#GLM - Bike Injuries
bike_injury <- glm(BikeInjuri ~ bike_priority_districts + enhanced_crossings + speed_humps + left_turn_traffic_calming + arterial_slow_zones + signal_timing + street_improvement_projects_corridors + neighborhood_slow_zones, family = "binomial", data = d.in)

summary(bike_injury)
exp(coef(bike_injury))
exp(confint(bike_injury))

#build table to plot Odds Ratios
a <- data.frame(exp(coef((bike_injury))))

a <- cbind(attribute = rownames(a), a)
rownames(a) <- 1:nrow(a)

b <- data.frame(exp(confint((bike_injury))))
b <- cbind(attribute = rownames(b), b)
rownames(b) <- 1:nrow(b)

coef_df <- left_join(a, b, by = "attribute")
colnames(coef_df)[2] <- "coefficient"
colnames(coef_df)[3] <- "lower_bound"
colnames(coef_df)[4] <- "upper_bound"

g <- ggplot(coef_df, aes(x = attribute, y = coefficient)) +
  geom_point(size = 2) +
  geom_errorbar(aes(ymax = upper_bound, ymin = lower_bound), width=0.1, color="darkred") + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) + 
  geom_text(data = coef_df, aes(label = round(coefficient, digits=3)), hjust = 1.2) +
  ggtitle("Bike Injuries - Coefficients & Confidence Intervals")

plot(g)

#GLM - MVO Injuries
mvo_injury <- glm(MVOInjurie ~ arterial_slow_zones + enhanced_crossings + speed_humps + left_turn_traffic_calming + street_improvement_projects_corridors + neighborhood_slow_zones, family = "binomial", data = d.in)

summary(mvo_injury)
exp(coef(mvo_injury))
exp(confint(mvo_injury))

#build table to plot Odds Ratios
a <- data.frame(exp(coef((mvo_injury))))

a <- cbind(attribute = rownames(a), a)
rownames(a) <- 1:nrow(a)

b <- data.frame(exp(confint((mvo_injury))))
b <- cbind(attribute = rownames(b), b)
rownames(b) <- 1:nrow(b)

coef_df <- left_join(a, b, by = "attribute")
colnames(coef_df)[2] <- "coefficient"
colnames(coef_df)[3] <- "lower_bound"
colnames(coef_df)[4] <- "upper_bound"

g <- ggplot(coef_df, aes(x = attribute, y = coefficient)) +
  geom_point(size = 2) +
  geom_errorbar(aes(ymax = upper_bound, ymin = lower_bound), width=0.1, color="darkred") + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) + 
  geom_text(data = coef_df, aes(label = round(coefficient, digits=3)), hjust = 1.2) +
  ggtitle("Motor Vehicle Injuries - Coefficients & Confidence Intervals")

plot(g)
```

**Build Predictive Model**
```{r}
#GENERAL INJURY 
#split data 70-30

set.seed(123)  
t_index <- sample(seq_len(nrow(d.in)), size = floor(.70*nrow(d.in)), replace = F)

d.train <- d.in[t_index, ]
d.test <- d.in[-t_index, ] 

#train logistic regression take 1 (all)
m.log <- glm(Injuries ~ bike_priority_districts + vz_priority_corridors + vz_priority_intersections + vz_priority_zones + enhanced_crossings + speed_humps + left_turn_traffic_calming + arterial_slow_zones + leading_pedestrian_interval_signals + signal_timing + safe_streets_for_seniors + street_improvement_projects_corridors, data = d.train, family = "binomial")

 #bike_priority_districts + vz_priority_corridors + vz_priority_intersections + vz_priority_zones +
#train logistic regression take 2 (only real safety features)
#m.log <- glm(Injuries ~ enhanced_crossings + speed_humps + left_turn_traffic_calming + arterial_slow_zones + leading_pedestrian_interval_signals + signal_timing + safe_streets_for_seniors + street_improvement_projects_corridors + neighborhood_slow_zones, data = d.train, family = "binomial")

#train logistic regression take 3 (only problem zones)
#m.log <- glm(Injuries ~ bike_priority_districts + vz_priority_corridors + vz_priority_intersections + vz_priority_zones, data = d.train, family = "binomial")

#predict injury
d.test$Predicted_Injury <- predict(m.log, newdata = d.test, type = "response")

#optimal cutoff seems to be 0.1
d.test$Predicted_Injury <- ifelse(d.test$Predicted_Injury >= 0.1,
                                   1,
                                   0) 

# TP
tp <- d.test %>%
  filter(Injuries == 1 & Predicted_Injury == 1) %>% nrow()
# TN
tn <- d.test %>%
  filter(Injuries == 0 & Predicted_Injury == 0) %>% nrow()
# FP
fp <- d.test %>%
  filter(Injuries == 0 & Predicted_Injury == 1) %>% nrow()
# FN
fn <- d.test %>%
  filter(Injuries == 1 & Predicted_Injury == 0) %>% nrow()

# Sensitivity (or TPR)
sens <- tp/(tp+fn)

# Specificity ( 1 - FPR)
spec <- 1 - (tn/(tn+fp))

# Accuracy
acc <- (fp+tp)/(tp+tn+fp+fn)

#find AUC
pred <- prediction(predictions = d.test$Predicted_Injury, labels = d.test$Injuries)
roc.perf <- performance(pred, measure = "tpr", x.measure = "fpr")

plot(roc.perf)

auc.perf <- performance(pred, measure = "auc")
auc.perf@y.values
```
**Decision Tree**
```{r}

#Build Decision Tree
mtree.1 <- rpart(Injuries ~ enhanced_crossings + speed_humps + left_turn_traffic_calming + arterial_slow_zones + leading_pedestrian_interval_signals + signal_timing + safe_streets_for_seniors + street_improvement_projects_corridors, data=d.train, method="class")

rpart.plot(mtree.1)

#Plot variables of importance
d.var_imp <-data.frame(mtree.1$variable.importance)
names(d.var_imp) <- "importance"
d.var_imp$variable <-as.factor(rownames(d.var_imp))
d.var_imp <-transform(d.var_imp, variable=reorder(variable, -importance) )

filt5 <- d.var_imp %>% top_n(-5)

g <-ggplot(filt5,aes(x=variable, y=importance)) + 
  geom_bar(stat="identity") + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
plot(g) 
```

**Random Forest**
```{r}

#Generate RF
mrf.1 <- randomForest(Injuries ~ enhanced_crossings + speed_humps + left_turn_traffic_calming + arterial_slow_zones + leading_pedestrian_interval_signals + signal_timing + safe_streets_for_seniors + street_improvement_projects_corridors, data=d.train, importance = TRUE, ntree=1000)

#plot variables of importance
varImpPlot(mrf.1)

#plot OOB error
mrf.1$importance
x <- gg_error(mrf.1)
plot(x)

#predict diagnosis (tree)
d.test$Predicted_Injury <- predict(mtree.1, d.test, type="class")

#form prediction object
tree_pred <- prediction(predictions=as.numeric(d.test$Predicted_Injury), labels =as.numeric(d.test$Injuries))

#calculate AUC
auc.perf <- performance(tree_pred, measure = "auc")
tree_auc <- auc.perf@y.values

#predict diagnosis (forest)
d.test$Predicted_Injury <- predict(mrf.1, d.test, type="class")

#form prediction object (forest)
rf_pred <-prediction(predictions=as.numeric(d.test$Predicted_Injury), labels =as.numeric(d.test$Injuries))

#calculate auc
auc.perf <- performance(rf_pred, measure = "auc")
rf_auc <- auc.perf@y.values

tree_auc
rf_auc

```

**Pedestrian Injury Predictions**
```{r}
#PEDESTRIAN INJURY 
set.seed(123)  
t_index <- sample(seq_len(nrow(d.in)), size = floor(.70*nrow(d.in)), replace = F)

d.train <- d.in[t_index, ]
d.test <- d.in[-t_index, ] 

#train logistic regression 
m.log <- glm(PedInjurie ~ arterial_slow_zones + enhanced_crossings + speed_humps + left_turn_traffic_calming + leading_pedestrian_interval_signals + street_improvement_projects_corridors + neighborhood_slow_zones, family = "binomial", data = d.test)


#predict injury
d.test$Predicted_Injury <- predict(m.log, newdata = d.test, type = "response")

#optimal cutoff seems to be 0.1
d.test$Predicted_Injury <- ifelse(d.test$Predicted_Injury >= 0.05,
                                   1,
                                   0) 

# TP
tp <- d.test %>%
  filter(Injuries == 1 & Predicted_Injury == 1) %>% nrow()
# TN
tn <- d.test %>%
  filter(Injuries == 0 & Predicted_Injury == 0) %>% nrow()
# FP
fp <- d.test %>%
  filter(Injuries == 0 & Predicted_Injury == 1) %>% nrow()
# FN
fn <- d.test %>%
  filter(Injuries == 1 & Predicted_Injury == 0) %>% nrow()

# Sensitivity (or TPR)
sens <- tp/(tp+fn)

# Specificity ( 1 - FPR)
spec <- tn/(tn+fp)

# Accuracy
acc <- (fp+tp)/(tp+tn+fp+fn)

# FPR (1- Specificity)
1 - (tn/(tn+fp))

# FNR
fn/(fn+tp)

#find AUC
pred <- prediction(predictions = d.test$Predicted_Injury, labels = d.test$Injuries)
roc.perf <- performance(pred, measure = "tpr", x.measure = "fpr")

plot(roc.perf)

auc.perf <- performance(pred, measure = "auc")
auc.perf@y.values



```
**Bike Injury**
```{r}
#BIKE INJURY 
set.seed(123)  
t_index <- sample(seq_len(nrow(d.in)), size = floor(.70*nrow(d.in)), replace = F)

d.train <- d.in[t_index, ]
d.test <- d.in[-t_index, ] 

#train logistic regression 
m.log <- glm(BikeInjuri ~ enhanced_crossings + speed_humps + left_turn_traffic_calming + arterial_slow_zones + signal_timing + street_improvement_projects_corridors + neighborhood_slow_zones, family = "binomial", data = d.test)


#predict injury
d.test$Predicted_Injury <- predict(m.log, newdata = d.test, type = "response")

#optimal cutoff seems to be 0.1
d.test$Predicted_Injury <- ifelse(d.test$Predicted_Injury >= 0.03,
                                   1,
                                   0) 

# TP
tp <- d.test %>%
  filter(Injuries == 1 & Predicted_Injury == 1) %>% nrow()
# TN
tn <- d.test %>%
  filter(Injuries == 0 & Predicted_Injury == 0) %>% nrow()
# FP
fp <- d.test %>%
  filter(Injuries == 0 & Predicted_Injury == 1) %>% nrow()
# FN
fn <- d.test %>%
  filter(Injuries == 1 & Predicted_Injury == 0) %>% nrow()

# Sensitivity (or TPR)
sens <- tp/(tp+fn)

# Specificity ( 1 - FPR)
spec <- tn/(tn+fp)

# Accuracy
acc <- (fp+tp)/(tp+tn+fp+fn)

# FPR (1- Specificity)
1 - (tn/(tn+fp))

# FNR
fn/(fn+tp)

#find AUC
pred <- prediction(predictions = d.test$Predicted_Injury, labels = d.test$Injuries)
roc.perf <- performance(pred, measure = "tpr", x.measure = "fpr")

plot(roc.perf)

auc.perf <- performance(pred, measure = "auc")
auc.perf@y.values


```
**MVO Injury**
```{r}
#MVO INJURY 
set.seed(123)  
t_index <- sample(seq_len(nrow(d.in)), size = floor(.70*nrow(d.in)), replace = F)

d.train <- d.in[t_index, ]
d.test <- d.in[-t_index, ] 

#train logistic regression 
m.log <- glm(MVOInjurie ~ arterial_slow_zones + enhanced_crossings + speed_humps + left_turn_traffic_calming + street_improvement_projects_corridors + neighborhood_slow_zones, family = "binomial", data = d.test)


#predict injury
d.test$Predicted_Injury <- predict(m.log, newdata = d.test, type = "response")

#optimal cutoff seems to be 0.1
d.test$Predicted_Injury <- ifelse(d.test$Predicted_Injury >= 0.1,
                                   1,
                                   0) 

# TP
tp <- d.test %>%
  filter(Injuries == 1 & Predicted_Injury == 1) %>% nrow()
# TN
tn <- d.test %>%
  filter(Injuries == 0 & Predicted_Injury == 0) %>% nrow()
# FP
fp <- d.test %>%
  filter(Injuries == 0 & Predicted_Injury == 1) %>% nrow()
# FN
fn <- d.test %>%
  filter(Injuries == 1 & Predicted_Injury == 0) %>% nrow()

# Sensitivity (or TPR)
sens <- tp/(tp+fn)

# Specificity ( 1 - FPR)
spec <- tn/(tn+fp)

# Accuracy
acc <- (fp+tp)/(tp+tn+fp+fn)

# FPR (1- Specificity)
1 - (tn/(tn+fp))

# FNR
fn/(fn+tp)

#find AUC
pred <- prediction(predictions = d.test$Predicted_Injury, labels = d.test$Injuries)
roc.perf <- performance(pred, measure = "tpr", x.measure = "fpr")

plot(roc.perf)

auc.perf <- performance(pred, measure = "auc")
auc.perf@y.values
```

